[package]
name = "icydb-error"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
candid = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
